repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check (run "ruff check")
        entry: ruff
        language: system
        types: [python]
        files: '^src/pynbodyext/'               # only trigger in src
        args: ["check"]
        pass_filenames: true
      - id: mypy
        name: mypy (run "mypy")
        entry: mypy
        language: system
        types: [python]
        files: '^src/pynbodyext/'               # only trigger in src
        args: ["--config-file=pyproject.toml"]
        pass_filenames: true