[package]
name = "pynbodyext-rust"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27", features = ["extension-module", "auto-initialize"] }
numpy = { version = "0.27"}
ndarray = "0.17"
rayon = "1.10"
gravity = { path = "../gravity" }
